// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPfF814hfiDnhaeEd9x6zKqdEST6WiqdY',
    appId: '1:633620701331:web:648b2b4e3679d31e9c2d66',
    messagingSenderId: '633620701331',
    projectId: 'joke-app-mis',
    authDomain: 'joke-app-mis.firebaseapp.com',
    storageBucket: 'joke-app-mis.firebasestorage.app',
    measurementId: 'G-BS31NPDCBD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDninR7m3dniaa6sgL6dPN52jtld6hGznw',
    appId: '1:633620701331:ios:feb8ee1a5201ce559c2d66',
    messagingSenderId: '633620701331',
    projectId: 'joke-app-mis',
    storageBucket: 'joke-app-mis.firebasestorage.app',
    iosBundleId: 'com.example.jokeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDninR7m3dniaa6sgL6dPN52jtld6hGznw',
    appId: '1:633620701331:ios:feb8ee1a5201ce559c2d66',
    messagingSenderId: '633620701331',
    projectId: 'joke-app-mis',
    storageBucket: 'joke-app-mis.firebasestorage.app',
    iosBundleId: 'com.example.jokeApp',
  );
}
